ALTER TABLE warehouse      ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users          ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE sector         ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE product        ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders         ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;